version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:15.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: wholesale
    ports:
      - "5001:5432"
    restart: unless-stopped