version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: igd
    ports:
      - "5001:5432"
    restart: unless-stopped
