springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5001/igd
    username: admin
    password: admin

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /wholesale