springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

spring:
  application:
    name: Account Service
  datasource:
    url: jdbc:postgresql://localhost:5001/wholesale
    username: admin
    password: admin

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /wholesale
  port: 8080

logging:
  level:
    root: INFO